# Generated by Django 3.2.13 on 2022-05-17 12:28

import another.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('another', '0002_delete_straceinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Straceinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elf_name', models.CharField(max_length=200)),
                ('params', models.CharField(default=' ', max_length=200)),
                ('msg', djongo.models.fields.ArrayField(model_container=another.models.jilu)),
            ],
        ),
    ]
