# Generated by Django 3.2.13 on 2022-05-10 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_perfmess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfmess',
            name='itlb_cache',
        ),
        migrations.RemoveField(
            model_name='perfmess',
            name='l1_icache',
        ),
    ]
