# Generated by Django 3.2.13 on 2022-05-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20220510_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='bintime',
            name='params',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
