# Generated by Django 3.2.13 on 2022-05-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_bintime_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stracemess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elf_name', models.CharField(max_length=200)),
                ('params', models.CharField(max_length=200)),
                ('run_time', models.DateTimeField(auto_now_add=True)),
                ('write_avgsec', models.DecimalField(decimal_places=0, max_digits=12)),
                ('write_times', models.DecimalField(decimal_places=0, max_digits=12)),
                ('read_avgsec', models.DecimalField(decimal_places=0, max_digits=12)),
                ('read_times', models.DecimalField(decimal_places=0, max_digits=12)),
                ('close_avgsec', models.DecimalField(decimal_places=0, max_digits=12)),
                ('close_times', models.DecimalField(decimal_places=0, max_digits=12)),
                ('openat_avgsec', models.DecimalField(decimal_places=0, max_digits=12)),
                ('openat_times', models.DecimalField(decimal_places=0, max_digits=12)),
                ('stat_avgsec', models.DecimalField(decimal_places=0, max_digits=12)),
                ('stat_times', models.DecimalField(decimal_places=0, max_digits=12)),
                ('munmap_avgsec', models.DecimalField(decimal_places=0, max_digits=12)),
                ('munmap_times', models.DecimalField(decimal_places=0, max_digits=12)),
                ('fstat_avgsec', models.DecimalField(decimal_places=0, max_digits=12)),
                ('fstat_times', models.DecimalField(decimal_places=0, max_digits=12)),
                ('accept_avgsec', models.DecimalField(decimal_places=0, max_digits=12)),
                ('accept_times', models.DecimalField(decimal_places=0, max_digits=12)),
                ('mmap_avgsec', models.DecimalField(decimal_places=0, max_digits=12)),
                ('mmap_times', models.DecimalField(decimal_places=0, max_digits=12)),
            ],
        ),
    ]
